[workspace]
resolver = "3"
members = ["crates/execution", "crates/checkpoint", "crates/validator"]

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "Apache-2.0"
publish = false

[workspace.dependencies]
checkpoint = { path = "crates/checkpoint" }
execution = { path = "crates/execution" }

bincode = "1.3.3"
serde = { version = "1.0.163", features = ["derive"] }

dag = { git = "https://github.com/asonnino/mysticeti", rev = "5a093a2223bda5cca1d15ee6bee97438782ab32e" }
replica = { git = "https://github.com/asonnino/mysticeti", rev = "5a093a2223bda5cca1d15ee6bee97438782ab32e" }
simulator = { git = "https://github.com/asonnino/mysticeti", rev = "5a093a2223bda5cca1d15ee6bee97438782ab32e" }

[profile.release]
panic = "abort"
debug = 1
