[package]
name = "cli"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "validator"
path = "src/main.rs"

[dependencies]
clap.workspace = true
dag.workspace = true
execution = { workspace = true, features = ["test-utils"] }
eyre.workspace = true
orchestrator.workspace = true
replica.workspace = true
serde.workspace = true
serde_yaml.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal"] }
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
validator = { workspace = true, features = ["benchmark"] }
